# Generated by Django 4.2.5 on 2023-09-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="due_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="start_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
