# Generated by Django 4.2.5 on 2023-09-06 22:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_alter_project_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0003_alter_tasks_due_date_alter_tasks_start_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tasks",
            new_name="Task",
        ),
    ]
